### ISSUE TITLE
npm name SyntaxError: Unexpected identifier await

### ISSUE THREAD

**Issue by LeeMeeTed** [ericblade/mws-advanced#7]
Hi ericblade,
I am trying to install "mws-advanced", but turned out it is not in npm. How can I use your npm package?
thanks

**Comment by ericblade** [comment]
I have not submitted to npm because it doesn't contain all the mws
functions yet, nor is it tested fully for what it does have. :)

You can npm install using the GitHub link though !

**Comment by LeeMeeTed** [comment]
Hi eric,
Yes, thank you. I can install it via GitHub link, sorry I am new :(
However, I can't use any of them most of the time it shows this error
```
const result = await mws.getMatchingProductForId({
                     ^^^
SyntaxError: Unexpected identifier
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
```
It is a good concept though, I will keep on following your project.
Thanks eric!

**Comment by ericblade** [comment]
Closing as this is just requiring a more up to date version of node
